### ISSUE TITLE
Auth API v2: Refactor frontend to use resources rather than AuthLevels

### ISSUE THREAD

**Issue by seanjparker** [unicsmcr/hs_apply#74]
The frontend still uses the `AuthLevels` which are passed as express 'locals' to the EJS template.

We need to refactor the frontend to support resources (from hs_auth) instead.

**Comment by kzalys** [comment]
The following PR can be used as an example for resolving this issue: https://github.com/unicsmcr/hs_auth/pull/132

Though we can probably get away with having something much simpler than in `hs_auth`

**Comment by seanjparker** [comment]
Added in #73
